stages:
  - build
  - deploy-dev
  - deploy-stage

build:
  stage: build
  only:
    - dev
    - stage
  tags:
    - front-common
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" >
      /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.$CI_COMMIT_REF_NAME
      --destination $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME


deploy-dev:
  image: alpine:latest
  stage: deploy-dev
  only:
    - dev
  tags:
    - front-common
  script:
    - chmod og= $DEV_KEY
    - apk update && apk add openssh-client
    - ssh -i $DEV_KEY -o StrictHostKeyChecking=no deployer@$DEV_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -i $DEV_KEY -o StrictHostKeyChecking=no deployer@$DEV_IP "docker pull $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    - ssh -i $DEV_KEY -o StrictHostKeyChecking=no deployer@$DEV_IP "docker stop tales_yokassa_payment_dev || true && docker rm tales_yokassa_payment_dev || true"
    - ssh -i $DEV_KEY -o StrictHostKeyChecking=no deployer@$DEV_IP "docker run --restart always --name tales_yokassa_payment_dev -p 46301:8000
      -d $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"

deploy-stage:
  image: alpine:latest
  stage: deploy-stage
  only:
    - stage
  tags:
    - front-common
  script:
    - chmod og= $STAGE_KEY
    - apk update && apk add openssh-client
    - ssh -i $STAGE_KEY -o StrictHostKeyChecking=no deployer@$STAGE_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -i $STAGE_KEY -o StrictHostKeyChecking=no deployer@$STAGE_IP "docker pull $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    - ssh -i $STAGE_KEY -o StrictHostKeyChecking=no deployer@$STAGE_IP "docker stop tales_yokassa_payment_stage || true && docker rm tales_yokassa_payment_stage || true"
    - ssh -i $STAGE_KEY -o StrictHostKeyChecking=no deployer@$STAGE_IP "docker run --restart always --name tales_yokassa_payment_stage -p 46301:8000
      -d $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"


